GET http://localhost:9000

### login route

POST http://localhost:9000/auth/login
###

POST http://localhost:9000/auth/register
Content-Type: application/json

{
    "email":"sama123@gmail.com",
    "password":"1234aiza"
}

### referesh token route
POST http://localhost:9000/auth/refresh-token
###

DELETE  http://localhost:9000/auth/logout